### ISSUE TITLE
Suggestions & problem compiling Xcode project

### ISSUE THREAD

**Issue by 1951FDG** [fikovnik/ShiftIt#24]
Suggestion 1. Set absolute path to Carbon.framework
/System/Library/Frameworks/Carbon.framework

see screenshot (Get Info): http://db.tt/lxcCmsX

Suggestion 2. Set plug-in dependency for "PreferencesWindow.xib"
ShortcutRecorder.framework/Versions/A/Resources/ShortcutRecorder.ibplugin

see screenshot (Edit Project Settings): http://db.tt/ALwbDjc

Fix 3. For OS X 10.5.x users, compile and copy and use ShortcutRecorder.framework with embedded ibplugin (compiled with architecture set to Standard 32-bit Universal (i386,ppc) instead of 32/64-bit Universal)

Newly compiled ShortcutRecorder.framework with embedded ibplugin for 10.5.x users, can be downloaded here (compiled by me): http://db.tt/j9yO4WP

Reasons:
(ShifIt will not compile, throws error, strip: for architecture x86_64 object: /fikovnik-ShiftIt-c3eef77/ShiftIt/ShortcutRecorder.framework/Versions/A/Resources/ShortcutRecorder.ibplugin/Contents/MacOS/ShortcutRecorder malformed object)
(ShortcutRecorder.framework did not compile with architecture set to 32/64-bit Universal under OS X 10.5.6)

Problem 4. Bunch of errors like fikovnik-ShiftIt-c3eef77/ShiftIt/WindowSizer.m:66: error: syntax error before '**attribute**' (first error it throws, 16 errors in total, all the same type error)

Each line start with SINGLETON_BOILERPLATE_FULL, throws an error, error: syntax error before '**attribute**'

How can I fix this last issue I am having, to be able to compile ShifIt successfully.
