### ISSUE TITLE
The shiftit16 branch doesn't build in Xcode 4.3 or 4.4

### ISSUE THREAD

**Issue by pwnall** [fikovnik/ShiftIt#89]
I get the following error.

```
/Users/victor/Downloads/si/ShiftIt/ShiftIt/X11WindowDriver.m:380:40: error: __block attribute not allowed, only allowed on local variables
- (BOOL)getGeometry_:(__block NSRect *)geometryRef ofWindow:(Window *)windowRef error:(NSError **)error {
```

After removing `__block`, I get the following error in Xcode 4.4 (but it builds in Xcode 4.3):

```
Undefined symbols for architecture x86_64:
  "_objc_setProperty_atomic_copy", referenced from:
      -[PreferencesWindowController setDebugLoggingFile:] in PreferencesWindowController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
